# SwiftModalPicker document generator jazzy settings

copyright: Copyright 2021 moslienko
author: Pavel Moslienko
xcodebuild_arguments: [-target, SwiftModalPicker-iOS]
clean: true
output: ./Documentation
